attn_only: false
batch_per_log: 50
batch_size: 128
beta1: 0.9
beta2: 0.99
d_head: 32
d_model: 128
d_vocab_out: 2
epochs: 100
format: adj
lr_max: 0.001
lr_pct_start: 0.1
model: transformer
n_heads: 8
n_layers: 2
n_vertices: 10
pool_type: mean
positional_embedding_type: standard
seed: 2
train_path: data/n10_15-21_tn_vn/train.npz
use_attn_result: false
val_path: data/n10_15-21_tn_vn/val.npz
weight_decay: 0.1
